### ISSUE TITLE
Do something about the ALL CAPS OMIM names

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/disease-miner#1]
Should this be done upstream in the ingest?

**Comment by nlwashington** [comment]
I have cleaned these up in NIF.  

See: http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nif-0000-03216-7

**Comment by cmungall** [comment]
Excellent. I see these are already fixed in data/Homo_sapiens/Hs-disease-labels.txt 

I'll take it from here
