### ISSUE TITLE
Add links to KEGG IDs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/disease-miner#2]
Can go via RGD PW database

**Comment by nlwashington** [comment]
Here's the KEGG disease id to OMIM disease id map:
http://rest.genome.jp/link/disease/omim
(this is distinct from the pathway links, which we can also get directly here:
http://rest.genome.jp/link/pathway/ds

**Comment by nlwashington** [comment]
Also, I think that we could integrated these into uberdisease using their hierarchy:
http://www.kegg.jp/kegg-bin/download_htext?htext=br08402.keg&format=htext

note that the ids in the format 'H00042' are the disease ids, if prefixed with ds, like "ds:H00042"
